#############端口
server:
  port: 7777
######################数据库连接
spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-2zeby4mnv8511249xmo.mysql.rds.aliyuncs.com:3306/block?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: block@18
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMi  llis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

   ########################################################
   ###Redis (RedisConfiguration)
   ########################################################
 #   redis:
  #      host: 39.107.67.108  # Redis服务器地址
  #      port: 8082        #Redis服务器连接端口
   #    # password:         #Redis服务器连接密码（默认为空）
   #     timeout: 10000    # 连接超时时间（毫秒）
   # pool:
    #   max-idle: 20     # 连接池中的最大空闲连接
    #   min-idle: 0      # 连接池中的最小空闲连接
    #   max-active: 20   #连接池最大连接数（使用负值表示没有限制）
    #   max-wait: 2
#####################################
## redis集群配置

#redis:
#    cache:MapperScan
     #节点
#     clusterNodes:
#       192.168.101.131:7001,
#       192.168.101.131:7002,
#       192.168.101.131:7003,
#       192.168.101.129:7004,
#       192.168.101.129:7005,
#       192.168.101.129:7006,
#    commandTimeout: 5000
#    expireSeconds: 120

############################################
    #solr 相关配置
#    data:
#      solr:
        #host: http://192.168.101.129:8080/solr/
#        host: http://192.168.50.71:8080/solr/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cc.pojo

